### ISSUE TITLE
problems with the NuGet package (missing Xml libs and wrong version of FSharp.Core)

### ISSUE THREAD

**Issue by giacomociti** [giacomociti/FSharp.Data.Xsd#1]
repro:

With Visual Studio 2015 I created a new F# Console Application, targeting .NET framework 4.6.

Installed package `FSharp.Data.Xsd.0.0.2` (using menu 'Manage NuGet packages...' in project references).

This also installed `FSharp.Core.3.0.2` as a dependency.
Notice that the output from Package Manager include this:
	*Attempting to resolve dependencies for package 'FSharp.Data.Xsd.0.0.2' with DependencyBehavior 'Lowest'*
	

Even simple code (like that given as example in the [website](https://giacomociti.github.io/FSharp.Data.Xsd/)) initially won't compile because of missing references to the BCL libraries for Xml.
After referencing `System.Xml` and `System.Xml.Linq` it compiles but then it breaks at runtime:

	Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<System.String> FSharp.Data.Runtime.XmlRuntime.TryGetValue(FSharp.Data.Runtime.BaseTypes.XmlElement)'.
	   at Program.main(String[] argv)
	Press any key to continue . . .

This is clearly due to the version of FSharp.Core.
I read often about it, for example [here](http://fsharp.github.io/2015/04/18/fsharp-core-notes.html) and [here](https://github.com/fsharp/FSharp.Data/issues/398) but still I'm quite confused about this topic.

To fix things I added a binding redirect like this in the app.config:

 

    <runtime>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
     </assemblyBinding>
    </runtime>

But clearly this is a workaround.

There's something wrong in the way `FSharp.Data.Xsd` is built and packaged.
Missing Xml references is a minor issue but the FSharp.Core stuff is much more concerning.

**Comment by giacomociti** [comment]
It should be fixed in version 0.0.4.

**Comment by maestrow** [comment]
This bug is still present in 1.0.0

**Comment by giacomociti** [comment]
I hope it's not exactly the same. You need the binding redirect even when starting from scratch?

**Comment by maestrow** [comment]
Actually binding redirect still needed when creating new script in LINQPad. In project, created in VS.Code, all works fine without binding redirect.
