### ISSUE TITLE
Schema not parsing

### ISSUE THREAD

**Issue by sheganinans** [giacomociti/FSharp.Data.Xsd#10]
### Description

I have this example schema and I would expect it to work, yet it doesnt.

### Repro steps

```fsharp
type TestXml = XmlProvider<Schema = """
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
        <xs:complexType name="atest_req">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="btest_res">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="btest_req">
            <xs:sequence>
                <xs:element name="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="atest_res">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:element name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="data">
            <xs:sequence>
                <xs:element name="trans_no" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="total" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="test_status" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="result" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="trans_type" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="language" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="error" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="btest" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="reciever" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="printer" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="response" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="window" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="maximum " type="xs:string" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:schema>
    """>
```

### Expected behavior

This should parse and generate the type fine.

### Actual behavior

```Error	: The type provider 'ProviderImplementation.XmlProvider' reported an error: The provided sample is neither a file, nor a well-formed XML: The 'http://www.w3.org/2001/XMLSchema:element' element is not supported in this context.```

### Known workarounds

None

### Related information 

* Windows 10
* Master, 0.0.9
* .NET Runtime

**Comment by giacomociti** [comment]
Hi @sheganinans , thanks for using FSharp.Data.Xsd.
There are a couple of issues with the xsd, in fact the error is raised by the underlying BCL class when parsing the schema.  

The first issue is in `atest_res` where the element `message` should be inside the sequence, not outside (maybe an attribute was meant instead of an element).

The other issue is that many elements refer to `data` which is a complex type. The target of a `ref` should be an element, not a type.

    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
        <xs:complexType name="atest_req">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="btest_res">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="btest_req">
            <xs:sequence>
                <xs:element name="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:complexType name="atest_res">
            <xs:sequence>
                <xs:element ref="data" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
                <xs:attribute name="message" type="xs:string" />
        </xs:complexType>
        <xs:element name="data">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="trans_no" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="total" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="test_status" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="result" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="trans_type" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="language" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="error" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="btest" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="reciever" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="printer" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="response" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="window" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="maximum " type="xs:string" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:schema>

The above xsd works fine, after turning `message` into an attribute and `data` into an element.

Let me also point out that `FSharp.Data.Xsd` works only when there is at least one global element of a complex type, hence turning `data` into an element also helped in this regard.

A final note on the error message you got: 

> The provided sample is neither a file, nor a well-formed XML

this may be bit misleading in using the word _sample_ instead of _schema_.
This message originates in the [F# Data](http://fsharp.github.io/FSharp.Data/) infrastructure where types are provided based on samples and not on schema; this message should be improved to cover also the case of using xsd instead of samples, but for the moment I think we can tolerate this littel imprecision.

**Comment by giacomociti** [comment]
I'm closing this because I hope the explanation is clear enough. Of course my proposed changes to the provided xsd are only meant to fix it from a syntactic point of view.

**Comment by sheganinans** [comment]
I appreciate it, thanks!
