### ISSUE TITLE
0...n relationship in .xsd

### ISSUE THREAD

**Issue by RolandTLH** [giacomociti/FSharp.Data.Xsd#11]
Hi,

First of all, thank you for this library, it's very helpful ! 

I am a perfect newbie to coding and github so please accept all my apologies if I make mistakes or misuse in the following attempt.

I think I've an issue with XmlProvider and my .xsd scheme.

In my .xsd I have a Node "Reason" that is descendant of the Node "Point" with attributes minOccurs = 0 and maxOccurs = unbounded.

I was expecting the type "Point" to be created with an argument for "Reason" typed as an Option<Reason[]>. Instead of that the type "Point" requires an array of Reason[] and it's not optional.

here is the part of the .xsd

```
<xs:complexType name="Point">
	<xs:sequence>
		<xs:element name="Reason" type="Reason" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>
```

the behavior is the same with all the relationships build on minOccurs = 0 and maxOccurs = "unbounded". When minOccurs = 1 or maxOccurs = 1, it works fine.

I hope to be clear enough. If it's not an issue in XmlProvider, can you tell me how I can create a "Point" with no "Reason" ?

Roland

**Comment by giacomociti** [comment]
Hi @RolandTLH , I think the type provider is behaving as expected: when maxOccurs is unbounded (actually as soon as it is greater than one) an array is needed.
The only case in which we get an Option is when minOccurs = 0 and maxOccurs = 1, as you can see in the [getMultiplicity](https://github.com/giacomociti/FSharp.Data.Xsd/blob/master/src/FSharp.Data.Xsd/Xml/XsdInference.fs#L273) function.
If you need a Point with no Reason just use an empty array.

**Comment by RolandTLH** [comment]
Hi @giacomociti . Thank you for the answer and the solution. It works. I thought without trying that I couldn't pass an empty array. I guess it's the main lesson here : I should always try first.
